import type { Metadata } from 'next'
import Link from 'next/link'
import { scan } from '@agentverify/scanner'
import { ReportView } from '@/components/report/ReportView'

export const metadata: Metadata = {
  title: 'Demo Report',
  description: 'A realistic Agent Verify report for a synthetic Finance Operations Agent — demo data, generated by the real scan engine.',
}

// Synthetic demo agent — a finance operations assistant with accounting, payment, email, and
// database access. Realistic shape, not a real customer's code. Every finding shown below is
// produced by the actual scan engine running against this content, not hand-written.
const FINANCE_OPS_AGENT = `
const mcpServers = {
  "accounting": { command: "npx", args: ["-y", "@modelcontextprotocol/server-stripe"] }
}

const agent = {
  name: 'FinanceOpsAgent',
  tools: ['*'],
  permissions: 'all',
  systemPrompt: 'Follow the finance team\\'s instructions to reconcile invoices and process payments: ' + userInput,
  accountingApiKey: "sk_live_DEMO1234567890ABCDEF",
}

async function lookupInvoice(invoiceId) {
  return db.query('SELECT * FROM invoices WHERE id = ' + invoiceId)
}

async function notifyFinanceTeam(message) {
  return sendMail({ to: 'finance@example.com', subject: 'Payment processed', body: message })
}

export async function run(request) {
  const invoice = await lookupInvoice(request.invoiceId)
  const result = await stripe.transfers.create({
    amount: invoice.amount,
    destination: request.destinationAccount,
  })
  await notifyFinanceTeam(\`Transferred \${invoice.amount} to \${request.destinationAccount}\`)
  return result
}
`.trim()

export default function DemoReportPage() {
  const result = scan({ content: FINANCE_OPS_AGENT, fileName: 'finance-ops-agent.js', fileSize: FINANCE_OPS_AGENT.length, platform: 'Demo' })

  return (
    <main style={{ backgroundColor: 'var(--bg)' }} className="min-h-screen">
      <div className="mx-auto max-w-3xl px-4 pt-6 md:px-6">
        <div style={{ backgroundColor: '#7C3AED1A', border: '1px solid #7C3AED55' }} className="mb-2 flex flex-wrap items-center justify-between gap-3 rounded-2xl px-5 py-4">
          <div>
            {/* Dedicated token (not --accent-purple-text) — this banner's own translucent
                purple tint background needs more contrast margin than a solid surface does. */}
            <p style={{ color: 'var(--demo-banner-text)' }} className="text-xs font-bold uppercase tracking-[0.22em]">Demo report — synthetic data</p>
            <p style={{ color: 'var(--text-secondary)' }} className="mt-1 text-sm">
              This is a realistic <strong>Finance Operations Agent</strong> example, not a real customer scan. It was produced by running Agent Verify&apos;s actual scan engine against the synthetic code below, so the findings, score, and evidence are real output — just not from a real deployment.
            </p>
          </div>
          <Link href="/dashboard" className="shrink-0 rounded-xl bg-[#7C3AED] px-4 py-2.5 text-sm font-semibold text-white hover:opacity-90">Scan your own agent</Link>
        </div>
      </div>
      <ReportView
        report={result as unknown as Record<string, unknown>}
        verdict={result.verdict}
        riskScore={result.riskScore}
        riskLevel={result.riskLevel}
        fileName={result.metadata.fileName}
        platform={result.metadata.selectedPlatform}
        scannedAt={result.metadata.scannedAt}
        source="dashboard"
        findings={result.findings}
        categoryScores={result.categoryScores}
        bom={result.bom}
        isOwner={false}
        reportUrl="https://aimodularity.com/agentverify/report/demo/"
      />
    </main>
  )
}
