import { canonicalAttestationJson, type AttestationPayload, type SignedAttestation } from '@agentverify/scanner'

/**
 * Attestation signing — the ONLY place in this entire codebase that touches the Agent Verify
 * signing private key. This module is imported only by workers/api (never by apps/web, never
 * bundled into anything shipped to a browser). packages/scanner/src/attestation.ts, which IS
 * safe for the browser, only ever sees public keys and signatures, never this module.
 *
 * Key custody:
 * - LOCAL DEVELOPMENT: a throwaway key pair generated by
 *   `workers/api/scripts/generate-dev-signing-key.mjs`, stored in `workers/api/.dev.vars`
 *   (already gitignored repo-wide) as ATTESTATION_SIGNING_PRIVATE_KEY_JWK, and as
 *   ATTESTATION_ISSUER=agentverify-dev. This key is clearly DEV ONLY, never reused as
 *   production material, and never committed.
 * - PRODUCTION: the private key JWK must be provisioned as a Cloudflare Worker secret
 *   (`wrangler secret put ATTESTATION_SIGNING_PRIVATE_KEY_JWK`) or, for stronger custody, held in
 *   a proper KMS and only a signing capability (not the raw key) exposed to the Worker — that
 *   integration is out of scope for this module, but the module boundary here (signing isolated
 *   to one file, keyed off one env binding) is exactly what makes that swap possible later
 *   without touching anything else. A production key must never be generated by this codebase or
 *   checked into the repository in any form.
 *
 * Algorithm: ECDSA P-256 with SHA-256 (a.k.a. ES256) — a modern, widely-supported asymmetric
 * algorithm with first-class support in the Workers/browser Web Crypto API on both sides, so any
 * external system can verify an attestation with nothing more than the published public key and
 * a standard crypto library. No private key material is ever included in a signed attestation —
 * only the derived public key (its `d` value stripped).
 */

export interface AttestationSigningEnv {
  /** JSON-encoded EC (P-256) private key in JWK format, passed directly (used by tests/production Worker secrets, which never go through a dotenv-style file parser). Absent in an environment where attestation signing hasn't been configured — signing is then skipped, not faked. */
  ATTESTATION_SIGNING_PRIVATE_KEY_JWK?: string
  /** Same key, base64-encoded — the form workers/api/scripts/generate-dev-signing-key.mjs writes to .dev.vars, since base64 sidesteps any ambiguity in how a given dotenv-style parser (wrangler's included) handles quotes/escaping around embedded double quotes. Preferred over the plain field when both are present. */
  ATTESTATION_SIGNING_PRIVATE_KEY_JWK_B64?: string
  /** Identifies which signing key issued the attestation, e.g. "agentverify-dev" / "agentverify-prod". Never secret. */
  ATTESTATION_ISSUER?: string
}

/** Resolves the raw JSON string for the private key JWK from whichever env field is present — base64 form preferred. Returns null if neither is configured. */
function resolveJwkJson(env: AttestationSigningEnv): string | null {
  if (env.ATTESTATION_SIGNING_PRIVATE_KEY_JWK_B64) {
    try {
      return atob(env.ATTESTATION_SIGNING_PRIVATE_KEY_JWK_B64)
    } catch {
      return null
    }
  }
  return env.ATTESTATION_SIGNING_PRIVATE_KEY_JWK ?? null
}

function derivePublicJwk(privateJwk: JsonWebKey): JsonWebKey {
  // EC JWK public coordinates (kty/crv/x/y) ARE the public key — the private scalar lives only
  // in `d`. Stripping it is how you get "the public half" of an EC JWK; nothing else to derive.
  const { kty, crv, x, y } = privateJwk
  return { kty, crv, x, y, key_ops: ['verify'], ext: true }
}

let cachedPrivateKey: { jwkSource: string; key: CryptoKey } | null = null

async function importPrivateKey(privateKeyJwkJson: string): Promise<CryptoKey> {
  if (cachedPrivateKey && cachedPrivateKey.jwkSource === privateKeyJwkJson) return cachedPrivateKey.key
  const jwk = JSON.parse(privateKeyJwkJson) as JsonWebKey
  const key = await crypto.subtle.importKey('jwk', jwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign'])
  cachedPrivateKey = { jwkSource: privateKeyJwkJson, key }
  return key
}

/**
 * Signs an attestation payload. Returns null (never throws, never fabricates a signature) when
 * no signing key is configured for this environment — a scan must still succeed and be usable
 * without attestation, it just won't carry a signed attestation until a key is provisioned.
 */
export async function signAttestation(payload: AttestationPayload, env: AttestationSigningEnv): Promise<SignedAttestation | null> {
  const jwkJson = resolveJwkJson(env)
  if (!jwkJson) return null

  try {
    const privateJwk = JSON.parse(jwkJson) as JsonWebKey
    const key = await importPrivateKey(jwkJson)
    const data = new TextEncoder().encode(canonicalAttestationJson(payload))
    const signatureBuf = await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, data as BufferSource)
    const signature = base64Encode(signatureBuf)
    return {
      payload,
      signature,
      algorithm: 'ECDSA-P256-SHA256',
      publicKey: derivePublicJwk(privateJwk),
    }
  } catch (e) {
    console.error('Attestation signing failed:', e instanceof Error ? e.message : e)
    return null
  }
}

/** Exposes just the public verification key + issuer/algorithm — safe to serve at a public endpoint, contains no secret material. */
export function getAttestationPublicKeyInfo(env: AttestationSigningEnv): { publicKey: JsonWebKey; algorithm: 'ECDSA-P256-SHA256'; issuer: string } | null {
  const jwkJson = resolveJwkJson(env)
  if (!jwkJson) return null
  try {
    const privateJwk = JSON.parse(jwkJson) as JsonWebKey
    return {
      publicKey: derivePublicJwk(privateJwk),
      algorithm: 'ECDSA-P256-SHA256',
      issuer: env.ATTESTATION_ISSUER ?? 'agentverify-dev',
    }
  } catch {
    return null
  }
}

function base64Encode(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}
